name: Build and Publish Documentation to GitHub Pages
on:
  push:
    branches:
      - develop
      - master
    paths:
      # Only rebuild documentation when docs have changed
      - "docs/**"
      - ".github/workflows/publish_mkdocs.yml"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          publish_branch: gh-pages
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python setup.py install
          pip install mkdocs-material==8.5.11 mkdocs-jupyter==0.22.0 neoteroi-mkdocs==0.1.2 pdocs==1.0.1
          mv config.txt.sample config.txt
      - name: Update API docs
        run: |
          pdocs as_markdown -o docs/src/api --exclude_source --overwrite src API
      - name: Deploy Documentation
        run: python -m mkdocs  gh-deploy --force -f docs/mkdocs.yml
